ckanext/saeoss/blueprints/news.py
# -*- coding: utf-8 -*-
"""
A blueprint rendering new pages.
"""
from flask import Blueprint
from ckan.plugins import toolkit
import ckanext.pages.utils as utils
from .news_utils import list_news, news_edit_util, news_delete_util

news_blueprint = Blueprint(
    "news", __name__, template_folder="templates", url_prefix="/news"
)


@news_blueprint.route("/")
def index():
    """A blueprint rendering new template.

    """
    list_news()
    return toolkit.render("news.html", type="news")


def news_show(page):
    """A blueprint rendering new show.

    """
    return utils.pages_show(page, page_type="news")


def news_edit(page=None, data=None, errors=None, error_summary=None):
    """A blueprint rendering editing new.

    """
    return news_edit_util(page, data, errors, error_summary, "news")


def news_delete(page):
    """A blueprint rendering deleting new.

    """
    return news_delete_util(page, page_type="news")


news_blueprint.add_url_rule("/news", view_func=index)
news_blueprint.add_url_rule(
    "/news_edit", view_func=news_edit, endpoint="news_new", methods=["GET", "POST"]
)
news_blueprint.add_url_rule("/news/<page>", view_func=news_show)
news_blueprint.add_url_rule(
    "/news_edit/", view_func=news_edit, endpoint="news_edit", methods=["GET", "POST"]
)
news_blueprint.add_url_rule(
    "/news_edit/<page>",
    view_func=news_edit,
    endpoint="news_edit",
    methods=["GET", "POST"],
)
news_blueprint.add_url_rule("/news/<page>", view_func=news_show)
news_blueprint.add_url_rule(
    "/news_delete/<page>",
    view_func=news_delete,
    endpoint="news_delete",
    methods=["GET", "POST"],
)

ckanext/saeoss/templates/ckanext_pages/emc_base_form.html
{% import 'macros/form.html' as form %}
{% import 'macros/wysiwyg.html' as wysiwyg %}

{% set data = data or {} %}
{% set errors = errors or {} %}
{% set ckan_29_or_higher = h.ckan_version().split('.')[1] | int >= 9 %}

{% if type == 'org' %}
    {% set prefix = 'organization_pages_' %}
    {% set args = {'id': id} %}
{% elif type == 'group' %}
    {% set prefix = 'group_pages_' %}
    {% set args = {'id': id} %}
{% elif type == 'blog' %}
    {% set prefix = 'blog_' %}
    {% set args = {} %}
{% else %}
    {% if ckan_29_or_higher %}
       {% set prefix = '' %}
    {% else %}
       {% set prefix = 'pages_' %}
    {% endif %}
    {% set args = {} %}
{% endif %}

{% if ckan_29_or_higher %}
  {% set page_url = page %}
{% else %}
  {% set page_url = '/' + page %}
{% endif %}
{% if ckan_29_or_higher %}
   {% set prefix = 'pages.' + prefix %}
{% endif %}

{% set cancel_url = h.url_for(prefix + 'index', **args) %}
{% set slug_prefix = cancel_url ~ '/' %}
{% set slug_domain = h.url_for(prefix + 'index', qualified=true, **args) %}
{% if page %}
  {% if ckan_29_or_higher %}

    {% if type == 'org' %}
      {% set delete_url = h.url_for('pages.organization_pages_delete', page=page_url, **args) %}
    {% elif type == 'group' %}
      {% set delete_url = h.url_for('pages.group_pages_delete', page=page_url, **args) %}
    {% else %}
      {% set delete_url = h.url_for('news.news_delete', page=page_url, **args) %}
    {% endif %}
  {% else %}
    {% set delete_url = h.url_for('news.news_delete', page=page_url, **args) %}
  {% endif %}
{% endif %}

{% if type == 'news' %}
    {% if not page %}
      <h1>{{ _('Add News Article') }}</h1>
    {% else %}
      <h1>{{ _('Edit News Article') }}</h1>
    {% endif %}
    {% set url_placeholder = 'eg. my-news-article' %}
    {% set title_placeholder = _('eg. News Article Title') %}
{% endif %}


<form class="dataset-form pages-form" method="post" action="{{ action_url }}" data-module="basic-form" class="dataset-form">

  {% block errors %}{{ form.errors(error_summary) }}{% endblock %}

  {% block form_basic_fields %}
    {{ form.input('title', id='field-title', label=_('Title'), placeholder=title_placeholder, value=data.title, error=errors.title, classes=['control-full', 'control-large'], attrs={'data-module': 'slug-preview-target', 'class': 'form-control'}) }}

    {% set domain = slug_domain|replace("http://", "")|replace("https://", "") %}
    {% set attrs = {'data-module': 'slug-preview-slug', 'data-module-prefix': domain~'/', 'data-module-placeholder': '<page>'} %}
    {{ form.prepend('name', id='field-name', label=_('URL'), prepend=slug_prefix, placeholder=_(url_placeholder), value=data.name, error=errors.name, attrs=attrs) }}

    {{ form.input('publish_date', id='field-publish_date', label=_('Publish Date'), placeholder=_('2021-04-23'), value=data.publish_date, error=errors.publish_date, classes=[], attrs={'data-module': 'datepicker', 'data-date-format': 'yyyy-mm-dd'}) }}

  {% endblock %}

  {% block extra_pages_form %}
  {% endblock extra_pages_form %}

  {% block form_visibility_fields %}
    <div class="control-group form-group">
      <label for="field-private" class="control-label">{{ _('Visibility') }}</label>
      <div class="controls">
        <select id="field-private" class="form-control" name="private">
          {% for option in [(true, _('Private')), (false, _('Public'))] %}
          <option value="{{ option[0] }}" {% if option[0] == data.private %}selected="selected"{% endif %}>{{ option[1] }}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    {% if not hide_field_order %}
      <div class="control-group form-group">
        <label for="field-order" class="control-label">{{ _('Header Order') }}</label>
        <div class="controls">
          <select id="field-order" class="form-control" name="order">
              {% for option in [('', _('Not in Menu')), ('1','1'), ('2', '2'), ('3', '3') , ('4', '4')] %}
            <option value="{{ option[0] }}" {% if option[0] == data.order %}selected="selected"{% endif %}>{{ option[1] }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
    {% endif %}

  {% endblock %}

  {% block form_content %}
    {% set type = 'asset' if h.ckan_version().split('.')[1] | int >= 9 else 'resource' %}
    {% set editor = h.get_wysiwyg_editor() %}
    {% if editor == 'medium' %}
      {% if ckan_29_or_higher %}
        {% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/medium-js' %}
        {% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/medium-css' %}
      {% else %}
        {% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/medium' %}
      {% endif %}


      {{ wysiwyg.editor('content', id='field-content', label=_('Content'), placeholder=_('Enter content here'), value=data.content|safe, error=errors.content) }}
    {% elif editor == 'ckeditor' %}
      {% if ckan_29_or_higher %}
        {% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/main-js' %}
        {% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/main-css' %}
      {% else %}
        {% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/main' %}
      {% endif %}
      <div class="control-group">
          <label for="field-content-ck" class="control-label">{{ _('Content') }}</label>
      </div>
      <textarea id="field-content-ck" name="content" placeholder="{{_('My content')}}" data-module="ckedit" style="height:400px" data-module-site_url="{{ h.dump_json(h.url('/', locale='default', qualified=true)) }}"> {{ data.content }}</textarea>
    {% else %}
      {{ form.markdown('content', id='field-content', label=_('Content'), placeholder=_('Enter content here'), value=data.content, error=errors.content) }}
    {% endif %}

  {% endblock %}

  {% block form_actions %}
    <div class="form-actions">
      {% if not page %}
        <a class="btn btn-default pull-left" href="{{ cancel_url }}">{{ _('Cancel') }}</a>
        <button class="btn btn-primary" name="save" value="save" type="submit">{{ _('Add') }}</button>
      {% else %}

        {% block delete_button %}
          {% if h.check_access('ckanext_%spages_delete'|format(type ~ '_' if type in ('group', 'org') else ''), {'id': data.id})  %}
            {% set locale = h.dump_json({'content': _('Are you sure you want to delete this Page?')}) %}
            <a class="btn btn-danger pull-left" href="{{ delete_url }}" data-module="confirm-action" data-module-i18n="{{ locale }}">{% block delete_button_text %}{{ _('Delete') }}{% endblock %}</a>
          {% endif %}
        {% endblock %}

        <button class="btn btn-primary" name="save" value="save" type="submit">{{ _('Save') }}</button>
      {% endif %}
    </div>

  {% endblock %}
</form>

{% block scripts %}
  {% if ckan_29_or_higher %}
    <script src="/vendor/ckeditor/ckeditor.js"></script>
  {% endif %}
{% endblock %}

ckanext/saeoss/templates/ckanext_pages/news.html
{% extends 'page.html' %}
{% block bodytag %}{{ super() }} class="blog"{% endblock %}
{% block subtitle %}{{ c.page.title }}{% endblock %}

{% block primary_content %}
  <section class="module-content">
    {% if h.check_access('ckanext_pages_update') %}
        {% snippet 'ckanext_pages/snippets/pages_asset.html', name='pages/main-css' %}
        {% link_for _('Edit'), named_route='news.news_edit', page=c.page.name, class_='btn btn-primary pull-right', icon=h.pages_get_plus_icon() %}
    {% endif %}
    <h1 class="page-heading">{{ c.page.title }}</h1>
      {% if c.page.publish_date %}
         <span class="muted date"> {{ h.render_datetime(c.page.publish_date) }} </span>
      {% endif %}
    {% if c.page.content %}
      {% set editor = h.get_wysiwyg_editor() %}
      {% if editor %}
        <div>
            {{c.page.content|safe}}
        </div>
      {% else %}
        {{ h.render_content(c.page.content) }}
      {% endif %}
    {% else %}
      <p class="empty">{{ _('This news currently has no content') }}</p>
    {% endif %}
  </section>
{% endblock %}

{% block secondary_content %}
{% set news_list = h.get_recent_news(number=5, exclude=c.page.name) %}

  <div class="module module-narrow module-shallow">
    <h2 class="module-heading">
      {{ _('News') }}
    </h2>
    <div class="module-content">
        {% for news in news_list %}
            <div class="blog-title">
                <h3 class="dataset-heading">
                      <a href="{{ h.url_for('news.news_show', page='/' + news.name) }}">{{ news.title or news.name }}</a>
                    <br>
                    {% if news.publish_date %}
                        <small> {{ h.render_datetime(news.publish_date) }} </small>
                    {% endif %}
                </h3>
            </div>
            <div class="blog-content">
                {{ h.markdown_extract(news.content) }}
                {% if news.publish_date %}
                   <br>
                      <a class="btn btn-small btn-primary more" href="{{ h.url_for('news.news_show', page='/' + news.name) }}">{{ _('More') }}</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
  </div>

{% set type = 'asset' if h.ckan_version().split('.')[1] | int >= 9 else 'resource' %}
{% snippet 'ckanext_pages/snippets/pages_' ~ type ~ '.html', name='pages/blog-css' %}

{% endblock %}

ckanext/saeoss/templates/ckanext_pages/news_edit.html
{% extends 'ckanext_pages/news_edit_base.html' %}

{% block subtitle %}{{ _('Edit Article')}} {% endblock %}

{% block primary_content_inner %}
  {% snippet 'ckanext_pages/emc_base_form.html', page=page, data=data, errors=errors, type='news'%}
{% endblock %}

ckanext/saeoss/templates/ckanext_pages/news_edit_base.html
{% extends 'ckanext_pages/edit_base.html' %}

{% block subtitle %}{{ _('News Articles') }}{% endblock %}

{% block secondary_content %}
  <div class="module module-narrow module-shallow">
    <h2 class="module-heading">
      <i class="fa fa-info-circle icon-info-sign"></i>
      {{ _('News') }}
    </h2>
    <div class="module-content">
      {% trans %}
        <p>Add news articles to CKAN here.</p>
      {% endtrans %}
    </div>
  </div>
{% endblock %}