ckanext/saeoss/blueprints/contact.py
# -*- coding: utf-8 -*-
"""
A blueprint rendering contact page.
"""
from flask import Blueprint
from ckan.plugins import toolkit

contact_blueprint = Blueprint(
    "contact", __name__, template_folder="templates", url_prefix="/contact"
)


@contact_blueprint.route("/")
def index():
    """A blueprint rendering contact template.

    """
    return toolkit.render("contact.html")

ckanext/saeoss/blueprints/map.py
# -*- coding: utf-8 -*-
"""
A blueprint rendering map page.
"""
from flask import Blueprint
from ckan.plugins import toolkit

map_blueprint = Blueprint(
    "map", __name__, template_folder="templates", url_prefix="/map"
)


@map_blueprint.route("/")
def index():
    """A blueprint rendering map template.

    """
    return toolkit.render("map/map.html")

ckanext/saeoss/blueprints/news.py
# -*- coding: utf-8 -*-
"""
A blueprint rendering new pages.
"""
from flask import Blueprint
from ckan.plugins import toolkit
import ckanext.pages.utils as utils
from .news_utils import list_news, news_edit_util, news_delete_util

news_blueprint = Blueprint(
    "news", __name__, template_folder="templates", url_prefix="/news"
)


@news_blueprint.route("/")
def index():
    """A blueprint rendering new template.

    """
    list_news()
    return toolkit.render("news.html", type="news")


def news_show(page):
    """A blueprint rendering new show.

    """
    return utils.pages_show(page, page_type="news")


def news_edit(page=None, data=None, errors=None, error_summary=None):
    """A blueprint rendering editing new.

    """
    return news_edit_util(page, data, errors, error_summary, "news")


def news_delete(page):
    """A blueprint rendering deleting new.

    """
    return news_delete_util(page, page_type="news")


news_blueprint.add_url_rule("/news", view_func=index)
news_blueprint.add_url_rule(
    "/news_edit", view_func=news_edit, endpoint="news_new", methods=["GET", "POST"]
)
news_blueprint.add_url_rule("/news/<page>", view_func=news_show)
news_blueprint.add_url_rule(
    "/news_edit/", view_func=news_edit, endpoint="news_edit", methods=["GET", "POST"]
)
news_blueprint.add_url_rule(
    "/news_edit/<page>",
    view_func=news_edit,
    endpoint="news_edit",
    methods=["GET", "POST"],
)
news_blueprint.add_url_rule("/news/<page>", view_func=news_show)
news_blueprint.add_url_rule(
    "/news_delete/<page>",
    view_func=news_delete,
    endpoint="news_delete",
    methods=["GET", "POST"],
)

ckanext/saeoss/blueprints/saved_searches.py
import uuid
from flask import Blueprint, request, jsonify
from ckan.plugins import toolkit
from ckan import model
from ckan.common import c
from datetime import date, datetime

saved_searches_blueprint = Blueprint(
    "saved_searches",
    __name__,
    template_folder="templates",
    url_prefix="/saved_searches",
)


@saved_searches_blueprint.route("/")
def index():
    return toolkit.render("saved_searches.html")


@saved_searches_blueprint.route(
    "/save_search", methods=["GET", "POST"], strict_slashes=False
)
def save_current_search():
    """save the current search query with user_id.
    """
    query = request.json
    user_id = c.userobj.id
    saved_search_id = uuid.uuid4()
    saved_search_title = _get_saved_search_title(query)
    q = f""" insert into saved_searches values('{saved_search_id}', '{user_id}', '{query}', '{saved_search_title}','{datetime.now()}') """
    result = model.Session.execute(q)
    model.Session.commit()
    return jsonify({"status": 200})


def _get_saved_search_title(query):
    """
    takes the title from an input
    if the title is "" it returns
    the current date.
    :param
    query:Search parameters.
    :type
    query:str
    """
    query_str = "q=" in query
    query_input = query.split("&", 1)[0]
    current_date = date.today().strftime("%m/%d/%Y")
    if not query_str:
        return "Query saved on " + current_date.replace("/", "-")
    else:
        return query_input.replace("q=", "") + " " + current_date.replace("/", "-")


@saved_searches_blueprint.route(
    "/delete_saved_search", methods=["GET", "POST"], strict_slashes=False
)
def delete_saved_search():
    """
    deletes a saved search via it's id.
    """
    if request.method == "POST":
        saved_search_id = request.json["saved_search_id"]
        q = f""" delete from saved_searches where saved_search_id ='{saved_search_id}' """
        model.Session.execute(q)
        model.Session.commit()
        return jsonify({"status": 200})

ckanext/saeoss/blueprints/sys_stats.py
# -*- coding: utf-8 -*-
"""
re-implement stats blueprint as it's not working
"""

import datetime
import logging
from typing import Any, ClassVar, Optional, Union

from sqlalchemy import Table, select, join, func, and_

import ckan.model as model

from flask import Blueprint
from ckan.plugins import toolkit


logger = logging.getLogger(__name__)

stats_blueprint = Blueprint(
    "stats", __name__, template_folder="templates", url_prefix="/stats"
)


_cumulative_num_pkgs = 0


@stats_blueprint.route("/")
def index():
    """A blueprint rendering stats template.
    """
    largestGroups = largest_groups()
    topTags = top_tags()
    topPackagesCreators = top_package_creators()
    mostEditedPackages = most_edited_packages()
    packageRevisions = get_by_week("package_revisions")
    packagesCreated = get_by_week("new_packages")
    packagesDeleted = get_deleted_packages()
    weeklyPackages = get_num_packages_by_week()
    allSubmittedDCPRRequests = get_submitted_dcpr_requests()
    weeklySubmittedDCPRRequests = get_weekly_submitted_dcpr_requests()

    return toolkit.render(
        "sys_stats.html",
        {
            "largest_groups": largestGroups,
            "top_tags": topTags,
            "top_packages_creators": topPackagesCreators,
            "most_edited_packages": mostEditedPackages,
            "package_revisions": packageRevisions,
            "packages_created": packagesCreated,
            "packages_deleted": packagesDeleted,
            "packages_per_week": weeklyPackages,
            "submitted_dcpr_requests":allSubmittedDCPRRequests,
            "dcpr_requests_per_week": weeklySubmittedDCPRRequests
        },
    )


DATE_FORMAT = "%Y-%m-%d"


def table(name: str):
    return Table(name, model.meta.metadata, autoload=True)


def datetime2date(datetime_: datetime.datetime):
    return datetime.date(datetime_.year, datetime_.month, datetime_.day)


def largest_groups(limit: int = 10) -> list[tuple[Optional[model.Group], int]]:
    package = table("package")
    activity = table("activity")

    j = join(activity, package, activity.c["object_id"] == package.c["id"])

    s = (
        select([package.c["owner_org"], func.count(package.c["id"])])
        .select_from(j)
        .group_by(package.c["owner_org"])
        .where(
            and_(
                package.c["owner_org"] != None,  # type: ignore
                activity.c["activity_type"] == "new package",
                package.c["private"] == False,
                package.c["state"] == "active",
            )
        )
        .order_by(func.count(package.c["id"]).desc())
        .limit(limit)
    )

    res_ids = model.Session.execute(s).fetchall()

    res_groups: list[tuple[Optional[model.Group], int]] = [
        (model.Session.query(model.Group).get(str(group_id)), val)
        for group_id, val in res_ids
    ]
    return res_groups


def top_tags(limit: int = 10, returned_tag_info: str = "object"):  # by package
    assert returned_tag_info in ("name", "id", "object")
    tag = table("tag")
    package_tag = table("package_tag")
    package = table("package")
    if returned_tag_info == "name":
        from_obj = [package_tag.join(tag)]
        tag_column = tag.c["name"]
    else:
        from_obj = None
        tag_column = package_tag.c["tag_id"]

    j = join(package_tag, package, package_tag.c["package_id"] == package.c["id"])
    s = (
        select(
            [tag_column, func.count(package_tag.c["package_id"])],
            from_obj=from_obj,
        )
        .select_from(j)
        .where(
            and_(
                package_tag.c["state"] == "active",
                package.c["private"] == False,
                package.c["state"] == "active",
            )
        )
    )
    s = (
        s.group_by(tag_column)
        .order_by(func.count(package_tag.c["package_id"]).desc())
        .limit(limit)
    )
    res_col = model.Session.execute(s).fetchall()
    if returned_tag_info in ("id", "name"):
        return res_col
    elif returned_tag_info == "object":
        res_tags = [
            (model.Session.query(model.Tag).get(str(tag_id)), val)
            for tag_id, val in res_col
        ]
        return res_tags


def top_package_creators(limit: int = 10) -> list[tuple[Optional[model.User], int]]:
    userid_count = (
        model.Session.query(
            model.Package.creator_user_id,
            func.count(model.Package.creator_user_id),
        )
        .filter(model.Package.state == "active")
        .filter(model.Package.private == False)
        .group_by(model.Package.creator_user_id)
        .order_by(func.count(model.Package.creator_user_id).desc())
        .limit(limit)
        .all()
    )
    user_count = [
        (model.Session.query(model.User).get(str(user_id)), count)
        for user_id, count in userid_count
        if user_id
    ]
    return user_count


def most_edited_packages(limit: int = 10) -> list[tuple[model.Package, int]]:
    package = table("package")
    activity = table("activity")

    s = (
        select(
            [package.c["id"], func.count(activity.c["id"])],
            from_obj=[
                activity.join(package, activity.c["object_id"] == package.c["id"])
            ],
        )
        .where(
            and_(
                package.c["private"] == False,
                activity.c["activity_type"] == "changed package",
                package.c["state"] == "active",
            )
        )
        .group_by(package.c["id"])
        .order_by(func.count(activity.c["id"]).desc())
        .limit(limit)
    )
    res_ids = model.Session.execute(s).fetchall()

    res_pkgs: list[tuple[model.Package, int]] = []
    for pkg_id, val in res_ids:
        pkg = model.Session.query(model.Package).get(str(pkg_id))
        assert pkg
        res_pkgs.append((pkg, val))

    return res_pkgs


def get_package_revisions() -> list[Any]:
    """
    @return: Returns list of revisions and date of them, in
                format: [(id, date), ...]
    """
    package = table("package")
    activity = table("activity")
    s = select(
        [package.c["id"], activity.c["timestamp"]],
        from_obj=[activity.join(package, activity.c["object_id"] == package.c["id"])],
    ).order_by(activity.c["timestamp"])
    res = model.Session.execute(s).fetchall()
    return res


def get_new_packages() -> list[tuple[str, int]]:
    """
    @return: Returns list of new pkgs and date when they were created, in
                format: [(id, date_ordinal), ...]
    """

    def new_packages() -> list[tuple[str, int]]:
        # Can't filter by time in select because 'min' function has to
        # be 'for all time' else you get first revision in the time period.
        package = table("package")
        activity = table("activity")
        s = (
            select(
                [package.c["id"], func.min(activity.c["timestamp"])],
                from_obj=[
                    activity.join(package, activity.c["object_id"] == package.c["id"])
                ],
            )
            .group_by(package.c["id"])
            .order_by(func.min(activity.c["timestamp"]))
        )
        res = model.Session.execute(s).fetchall()
        res_pickleable: list[tuple[str, int]] = []
        for pkg_id, created_datetime in res:
            res_pickleable.append((pkg_id, created_datetime.toordinal()))
        return res_pickleable

    return new_packages()


def get_deleted_packages():
    """
    @return: Returns list of deleted pkgs and date when they were deleted,
                in format: [(id, date_ordinal), ...]
    """

    def deleted_packages() -> list[tuple[str, int]]:
        # Can't filter by time in select because 'min' function has to
        # be 'for all time' else you get first revision in the time period.
        package = table("package")
        activity = table("activity")

        s = (
            select(
                [package.c["id"], func.min(activity.c["timestamp"])],
                from_obj=[
                    activity.join(package, activity.c["object_id"] == package.c["id"])
                ],
            )
            .where(activity.c["activity_type"] == "deleted package")
            .group_by(package.c["id"])
            .order_by(func.min(activity.c["timestamp"]))
        )
        res = model.Session.execute(s).fetchall()
        res_pickleable: list[tuple[str, int]] = []
        for pkg_id, deleted_datetime in res:
            res_pickleable.append((pkg_id, deleted_datetime.toordinal()))
        return res_pickleable

    return deleted_packages()


def get_date_week_started(date_: Union[datetime.datetime, datetime.date]):
    assert isinstance(date_, datetime.date)
    if isinstance(date_, datetime.datetime):
        date_ = datetime2date(date_)
    return date_ - datetime.timedelta(days=datetime.date.weekday(date_))


def get_by_week(object_type: str) -> list[tuple[str, list[str], int, int]]:
    _object_type = object_type

    def objects_by_week() -> list[tuple[str, list[str], int, int]]:
        if _object_type == "new_packages":
            objects = get_new_packages()

            def get_date(object_date):  # type: ignore
                return datetime.date.fromordinal(object_date)

        elif _object_type == "deleted_packages":
            objects = get_deleted_packages()

            def get_date(object_date):  # type: ignore
                return datetime.date.fromordinal(object_date)

        elif _object_type == "package_revisions":
            objects = get_package_revisions()

            def get_date(object_date):
                return datetime2date(object_date)

        else:
            raise NotImplementedError()
        first_date = (
            get_date(objects[0][1])  # type: ignore
            if objects
            else datetime.date.today()
        )
        week_commences = get_date_week_started(first_date)
        week_ends = week_commences + datetime.timedelta(days=7)

ckanext/saeoss/templates/base.html
{% ckan_extends %}

{% block meta %}
    {{ super() }}
    <meta name="title" content="{{ g.site_title }}" />
    <meta name="author" value="{{ h.get_seo_metatags('site_author') }}" />
    <meta name="description" content="{{ h.get_seo_metatags('site_description') }}" />
    <meta name="keywords" content="{{ h.get_seo_metatags('site_keywords') }}" />
{% endblock %}

{% block styles %}
{#    {{ super() }}#}
    {% asset 'ckanext-saeoss/ckan-base-css' %}
    {% asset 'ckanext-saeoss/saeoss-css' %}
    {% asset 'ckanext-saeoss/dataset-spatial-extent-map-css' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% asset 'ckanext-saeoss/xml-parser-js' %}
    {% asset 'ckanext-saeoss/custom-select-js' %}
    {% asset 'ckanext-saeoss/spatial-search-js' %}
    {% asset 'ckanext-saeoss/change-dataset-word-js' %}
    {% asset 'ckanext-saeoss/apply-save-search-js' %}
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="fa255ba6-f1be-4ba5-9507-7bd6e7addbf3";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
    {% asset "ckanext-saeoss/vendor-plot-js"  %}
    {# {% asset "ckanext-saeoss/plotter-js" %} #}
    {% asset "ckanext-saeoss/utils-js" %}





{% endblock %}

ckanext/saeoss/templates/contact.html
{% extends "page.html" %}
{% block subtitle %}{{ _("Contact Details") }}{% endblock %}
{% block content %}
    <div class="container">
    <section class="py-5 border-bottom" xmlns="http://www.w3.org/1999/html">
        <div class="text-center mb-5">
            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
            <h1 class="fw-bolder contact-title">Contact Details</h1>
        </div>
        <div class="row gx-5 justify-content-center">
            <div class="col-xs-6 col-sm-3">
                    <h5 class="mb-0 fw-bolder" style="color:#ec971f">Director: NSIF</h5>
                    <p class="text-muted">Ms Maroale (Mimi) Chauke</p>
                    <p class="text-muted">Tel: +27 12 312 9643</p>
                    <p class="text-muted">Mobile: 072 647 3935</p>
                    <p class="text-muted">Email: <u style="color:#3F7752">maroale.chauke@dalrrd.gov.za</u></p>
            </div>
            <div class="col-xs-6 col-sm-3">
                    <h5 class="mb-0 fw-bolder" style="color:#ec971f">Secretary: NSIF</h5>
                    <p class="text-muted">Ms Serati Manele</p>
                    <p class="text-muted">Tel: +27 12 312 8718</p>
                    <p class="text-muted"><u style="color:#3F7752">Email: serati.mashamaite@dalrrd.gov.za</u></p>
                    <h5 class="mb-0 fw-bolder" style="color:#ec971f">General Enquiries:</h5>
                    <p class="text-muted">nsif@drdlr.gov.za</p>
            </div>
            <div class="col-xs-6 col-sm-3">

                    <h5 class="mb-0 fw-bolder" style="color:#ec971f">Subdirectorate: Policy and Standards Facilitation</h5>
                    <p class="text-muted">VACANT</p>
                    <p class="text-muted">Tel: +27 12 312 8718</p>
                    <p class="text-muted">Email: <u style="color:#3F7752">NSIF@dalrrd.gov.za</u></p>
                    <h5 class="mb-0 fw-bolder" style="color:#ec971f">Subdirectorate: External Client Support</h5>
                    <p class="text-muted">Ms Nontobeko Nyuswa</p>
                    <p class="text-muted">Tel: +27 12 312 9110</p>
                    <p class="text-muted">Email: <u style="color:#3F7752">nontobeko.nyuswa@dalrrd.gov.za</u></p>
            </div>
            <div class="col-xs-6 col-sm-3">
                    <h5 class="mb-0 fw-bolder" style="color:#ec971f">Sub-directorate: Spatial Information and Support </h5>
                    <p class="text-muted">Mr Vutomi Ndlovu</p>
                    <p class="text-muted">Tel: +27 12 312 9415</p>
                    <p class="text-muted">Mobile: 084 400 6184</p>
                    <p class="text-muted">Email: <u style="color:#3F7752">Vutomi.Ndlovu@dalrrd.gov.za</u></p>
            </div>
                </div>
        </section>
    </div>
{% endblock %}
{% block scripts %}
    {{  super() }}
    {% asset "ckanext-saeoss/check-access-js" %}
    {% asset "ckanext-saeoss/xml-parser-js" %}
{% endblock %}

ckanext/saeoss/templates/footer.html
{% ckan_extends %}
{% set saeoss_version = h.saeoss_show_version() %}
{#
    below we reimplement the default footer_links block in order to include the current version of
    CKAN and of the Saeoss
#}
{% block footer_content %}
    <div class="content">
        <div class="footer-text">
            <p>Copyright ©  {{ h.get_year() }}- SAEOSS Portal {{ h.get_year() }}</p>
            <p>Powered by CKAN, developed by Kartoza</p>
            <p>Version: {{ h.get_release() }}</p>
        </div>

        {% block footer_lang %}
        {% endblock %}

    </div>
{% endblock %}
{# {% set saeoss_version = h.saeoss_show_version() %} #}

{#{% block footer_links %}#}
{#    <li>Saeoss v{{ saeoss_version.version }} (git sha: {{ saeoss_version.git_sha }})</li>#}
{#    <li>CKAN v{{ h.ckan_version() }}</li>#}
{#{% endblock %}#}

{% block footer_debug %}
{% endblock %}

ckanext/saeoss/templates/header.html
{% ckan_extends %}
{% block header_wrapper %}
    <nav class="navbar navbar-default border-bottom">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation-toggle" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ h.url_for('home.index') }}">
          <img src="/images/Logo.jpg" height="70">
      </a>
    </div>
      <div class="collapse navbar-collapse" id="main-navigation-toggle">
      {% block header_site_navigation %}
        <ul class="nav navbar-nav navbar-center">
            {% block header_site_navigation_tabs %}
                <li class="li-flex"> 
                  <a href="{{ url_for('dataset.search') }}" class="image" title="{{ _('Metadata') }}">{{ _('Metadata') }}</a>
                  <span class="hr-ver"></span>
                </li>
                <li class="li-flex">
                   <a href="{{ url_for('map.index') }}" class="image" title="{{ _('Map') }}">{{ _('Map') }}</a>
                   <span class="hr-ver"></span>
                  </li>
                <li class="li-flex"> 
                  <a href="{{ url_for('organization.index') }}" class="image" title="{{ _('Organisations') }}">{{ _('Organisations') }}</a>
                  <span class="hr-ver"></span>
                </li>
                <li class="li-flex"> 
                  <a href="{{ url_for('organization.index') }}" class="image" title="{{ _('About') }}">{{ _('About') }}</a>
                  <span class="hr-ver"></span>
                </li>
                <li> 
                  <a href="#" class="image" title="Help">Help</a>
                </li>
            {% endblock %}
        </ul>
      {% endblock %}
      <ul class="nav navbar-nav navbar-right">
        {% if c.userobj %}
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" data-testid="loggedin_user_icon"> {{ h.user_image((c.user if c and c.user else ''), size=22) }}
            <span class="username">{{ c.userobj.display_name }}</span></a>
                <ul class="dropdown-menu">
                    <li> <a href="{{ h.url_for('user.read', id=c.userobj.name) }}" class="image" title="{{ _('View profile') }}">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span class="text">{{ _('Profile') }}</span></a></li>
                    {% set new_activities = h.new_activities() %}
                    {% if h.saeoss_org_memberships(c.userobj.id) %}
                        <li>
                          <a href="{{ h.url_for('harvest.search') }}" title="{{ _('Harvesting Settings') }}">
                            <i class="fa fa-cloud" aria-hidden="true"></i>
                            <span class="text">{{ _('Harvesting Settings') }}</span>
                          </a>
                        </li>
                    {% endif %}
                    <li class="notifications {% if new_activities > 0 %}notifications-important{% endif %}">
                      {% set notifications_tooltip = ngettext('Dashboard (%(num)d new item)', 'Dashboard (%(num)d new items)',
                      new_activities)
                      %}
                      <a href="{{ h.url_for('dashboard.index') }}" title="{{ notifications_tooltip }}">
                        <i class="fa fa-tachometer" aria-hidden="true"></i>
                        <span class="text">{{ _('Dashboard') }}</span>
                        <span class="badge">{{ new_activities }}</span>
                      </a>
                    </li>
                    {% block header_account_settings_link %}
                    <li>
                      <a href="{{ h.url_for('user.edit', id=c.userobj.name) }}" title="{{ _('Profile settings') }}">
                        <i class="fa fa-cog" aria-hidden="true"></i>
                        <span class="text">{{ _('Profile settings') }}</span>
                      </a>
                    </li>
                    {% endblock %}
                    {% block header_usage_stats_link %}
                        <li>
                            <a href="{{ h.url_for('stats.index') }}" title="{{ _('Usage statistics') }}">
                                <i class="fa fa-pie-chart" aria-hidden="true"></i>
                                <span class="text">{{ _('Usage statistics') }}</span>
                            </a>
                        </li>
                    {% endblock %}
                        {% if c.userobj.sysadmin %}
                        <li>
                          <a href="{{ h.url_for('admin.index') }}" title="{{ _('Sysadmin settings') }}">
                            <i class="fa fa-gavel" aria-hidden="true"></i>
                            <span class="text">{{ _('Sysadmin settings') }}</span>
                          </a>
                        </li>
                        <li>
                          <a href="{{ h.url_for('validator.index') }}" title="{{ _('Metadata Validator') }}">
                            <i class="fa fa-check" aria-hidden="true"></i>
                            <span class="text">{{ _('Metadata Validator') }}</span>
                          </a>
                        </li>
                    {% endif %}
                    {#
                    This next section has been borrowed and adapted from ckanext-pages header.html template. One
                    notable difference is that we only show the pages-related nav items if the current user is allowed
                    to modify them. This means that we need to provide means for these contents to be visible elsewhere
                    like for example providing link to them via the main nav.
                    #}
                    {% if h.check_access('ckanext_pages_update') %}
                        <li>
                            <a href="{{ h.url_for('pages_index') }}" title="{{ _('Pages') }}">
                                <i class="fa fa-file icon-file" aria-hidden="true"></i>
                                <span class="text">{{ _('Pages') }}</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ h.url_for('pages.blog_index' if h.ckan_version().split('.')[1] | int >= 9 else 'blog_index') }}" title="{{ _('Blog') }}">
                                <i class="fa fa-pencil icon-pencil"></i>
                                <span class="text">{{ _('Blog') }}</span>
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{{ h.url_for('saved_searches.index') }}" title="{{ _('Saved Search') }}" data-testid="logout">
                                <i class="fa fa-bookmark-o" aria-hidden="true"></i>
                                <span class="text">{{ _('Saved Search') }}</span>
                            </a>
                    </li>
                    {% block header_account_log_out_link %}
                        <li>
                            <a href="{{ h.url_for('user.logout') }}" title="{{ _('Log out') }}" data-testid="logout">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                <span class="text">{{ _('Log out') }}</span>
                            </a>
                        </li>
                    {% endblock %}
                </ul>


        </li>
        {% else %}
        {% block header_account_notlogged %}
        <li data-testid="nav_login">{% link_for _('LOG IN'), named_route='user.login' %}</li>
        {% if h.check_access('user_create') %}
        <li>{% link_for _('SIGN UP'), named_route='user.register', class_='sub' %}</li>
        {% endif %} {% endblock %}
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

{% endblock %}

ckanext/saeoss/templates/news.html
{% extends 'page.html' %}

  {% set pages_total = pages|length %}
  {% set type='news' %}
  {% set action = '{0}_show'.format(type) %}
  {% set pages=c.page.items %}
  {% block content %}
    <div style="padding-left: 20px;">
      <br/>  <br/>
      {% link_for _('Add Article'), named_route='news.news_new', page='', class_='btn btn-primary', icon=h.pages_get_plus_icon() %}
      <h1 class="page-heading page-list-header" style="margin-top: 20px;">News</h1>
      {% if pages %}
        <div class="page-list">
          {% set editor = h.get_wysiwyg_editor() %}
          {% for page in pages %}
              {% set url = h.url_for('news.news_show', page=page.name) %}
              {%- snippet 'ckanext_pages/snippets/page_item.html', url=url, page=page -%}
          {% endfor %}
        </div>

      {% else %}
        <p class="empty">{{ _('There are currently no news articles here') }}</p>
      {% endif %}
  </div>
{% endblock %}

ckanext/saeoss/templates/saved_searches.html
{% extends "page.html" %}

{% set saved_searches = h.get_saved_searches() %}
{%- block content %}
    <div class="saved-searches-container" data-module="implement_saved_search">
        <div class="saved-searches-holder">
            {% if saved_searches|length < 1 %}
                <p class="module-content empty" style="margin-top: 30px;"> Currently you don't have any saved searches </p>
            {% else %}
                {% for search in saved_searches %}
                    <div class="saved-search-card">
                        <p>{{ search[0] }}</p>
                        <p id="saved_search_query" style="display: none;">{{ search[1] }}</p>
                        <p>{{ search[2].strftime("%Y-%m-%d %H:%M:%S") }}</p>
                        <p class="saved-search-id" style="display: none;"> {{ search[3] }} </p>
                        {% if c.userobj.sysadmin %}
                            <p class="saved-search-user label label-inverse"> {{ h.get_user_name(search[4]) }} </p>
                        {% endif %}
                        <div>
                            <button class="apply-saved-search btn btn-primary"> Apply saved search </button>
                            <button class="delete-saved-search btn btn-danger" data-search_id = "{{ search[3] }}" data-module="delete_saved_search"> Delete saved search </button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}